### ISSUE TITLE
[Improvement] Get display capable resolution instead of a static list

### ISSUE THREAD

**Issue by satsukiyatoshi** [tsunamods-codes/7th-Heaven#5] opened 2021-05-23 21:26 UTC
Find a way for 7th to check witch are the capable display's resolution.
This way any exotic display can use its resolutions.
Also it'll avoid classic fullHD display to be set up to 4K resolution

**Comment by barkermn01** [comment] 2021-05-24 09:56
After Talks on Discord, The plan is to use the WMI system to get the support resolutions directly from the Hardware system using the WMI,

E.G
```csharp
 public class SupportedResolutions{
        public UInt32 H {get; private set;}
        public UInt32 V {get; private set;}
        public UInt16 R {get; private set;}
        
        public SupportedResolutions(h,v,r){
            H = h;
            V = v;
            R = r;
        }
        
        public override string ToString() => $"{H}x{V}x{R}";
    }
 
 public class PrimaryScreen{
    
    public static List<SupportedResolutions> GetSupportedResolutions()
    {
        var scope = new System.Management.ManagementScope();
        var q = new System.Management.ObjectQuery("SELECT * FROM CIM_VideoControllerResolution");

        UInt32 maxHResolution;
        UInt32 maxVResolution;
        UInt16 maxRefresh;
        List<SupportedResolutions> resolutions = new List<SupportedResolutions>();
        
        using (var searcher = new System.Management.ManagementObjectSearcher(scope, q))
        {
            foreach (var item in results)
            {
                maxHResolution = (UInt32)item["HorizontalResolution"];
                maxVResolution = (UInt32)item["VerticalResolution"];
                maxRefresh = (UInt32)item["RefreshRate"];
                List.Add(new SupportedResolutions(maxHResolution, maxVResolution, maxRefresh));
            }
        }

        return resolutions;
    }
 }
 ```

This will then need handing over to a WPF programmer to tie into the UI layer correctly

**Comment by julianxhokaxhiu** [comment] 2021-06-06 12:54
The way currently the Game Driver configuration window is coded makes it really difficult to "inject" the flow and add custom options to it. At the moment the values are literally hardcoded in an XML and that XML acts as a boilerplate to draw the entire window ( see https://github.com/tsunamods-codes/7th-Heaven/blob/master/SeventhHeavenUI/Resources/7H_GameDriver_UI.xml#L36 ).

So before even understanding how to fetch resolutions, we would need to figure out how to change the draw flow and intercept the moment it draws the Resolution dropdown and add our detected custom options.

**Comment by barkermn01** [comment] 2021-06-08 10:18
I ran 7th heaven then the game then I tried to open the GameDriver settings window and I get the below error not sure what is causing this probably a pathing issue. but it prevents me from testing or working on this.

![image](https://user-images.githubusercontent.com/37368/121168757-360f3200-c84b-11eb-9f9e-629bc21fe11b.png)

**Comment by julianxhokaxhiu** [comment] 2021-06-08 10:28
This is the very first time I am being told about this issue to be honest. Not sure which steps are you taking, but would be useful to document them in order to be able to reproduce.

**Comment by barkermn01** [comment] 2021-06-08 11:21
The steps im following,

1. Building 7th heaven (latest code from the master branch) in debug mode in VS
2. Clicking Play,
3. Waiting for the game to load,
4. Alt-F4'ing the game,
5. Clicking the Cog Settings dropdown,
6. Clicking "Game Driver..."
7. Get presented with that.

I'm guessing it's a pathing problem but I'm not 100% sure.

**Comment by julianxhokaxhiu** [comment] 2021-06-08 15:01
Yes, looks like your FF7 installation was not detected correctly. The Game Driver window will search for an FFNx.toml file set in the `.FF7Path` propery, which is set in the General Settings window.

**Comment by julianxhokaxhiu** [comment] 2021-06-25 23:36
This item could be tackled by patching the Game Driver window class draw and organizer, hook the select box that is responsible for the resolution and instead of reading static items from the XML file, you could return an array of strings built based on the aforementioned POC.

If you need more info @barkermn01 ping me on Discord.

**Comment by barkermn01** [comment] 2021-06-27 21:19
This has been resolved in the latest canary.

**Closed by barkermn01** 2021-06-27 21:19 UTC
Labels: enhancement
